module.exports = {
    'DE_COUNTRY_NAMES': {
        'afghanistan': 'afghanistan',
        'albanien': 'albania',
        'algerien': 'algeria',
        'andorra': 'andorra',
        'angola': 'angola',
        'antarktis': 'antarctica',
        'antigua': 'antigua',
        'argentinien': 'argentina',
        'armenien': 'armenia',
        'australien': 'australia',
        'österreich': 'austria',
        'aserbaidschan': 'azerbaijan',
        'bahrain': 'bahrain',
        'bangladesch': 'bangladesh',
        'barbados': 'barbados',
        'weißrussland': 'belarus',
        'belgien': 'belgium',
        'belize': 'belize',
        'benin': 'benin',
        'bhutan': 'bhutan',
        'bolivien': 'bolivia',
        'bosnien': 'bosnia',
        'botswana': 'botswana',
        'brasilien': 'brazil',
        'brunei': 'brunei',
        'bulgarien': 'bulgaria',
        'burkina faso': 'burkina faso',
        'burundi': 'burundi',
        'kambodscha': 'cambodia',
        'kamerun': 'cameroon',
        'kanada': 'canada',
        'kap verde': 'cape verde',
        'tschad': 'chad',
        'chile': 'chile',
        'china': 'china',
        'columbia': 'colombia',
        'cookinseln': 'cook islands',
        'costa rica': 'costa rica',
        'elfenbeinküste': 'cote d’Ivoire',
        'kroatien': 'croatia',
        'kuba': 'cuba',
        'zypern': 'cyprus',
        'dänemark': 'denmark',
        'dschibuti': 'djibouti',
        'dominica': 'dominica',
        'osttimor': 'east timor',
        'ecuador': 'ecuador',
        'ägypten': 'egypt',
        'el salvador': 'el salvador',
        'ãquatorialguinea': 'equatorial guinea',
        'eritrea': 'eritrea',
        'estland': 'estonia',
        'fiji': 'fiji',
        'finnland': 'finland',
        'frankreich': 'france',
        'gabun': 'gabon',
        'georgia': 'georgia',
        'deutschland': 'germany',
        'ghana': 'ghana',
        'grossbritannien': 'great britain',
        'griechenland': 'greece',
        'grönland': 'greenland',
        'grenada': 'grenada',
        'guatamala': 'guatamala',
        'guinea': 'guinea',
        'guinea-bissau': 'guinea-bissau',
        'guyana': 'guyana',
        'haiti': 'haiti',
        'honduras': 'honduras',
        'ungarn': 'hungary',
        'island': 'iceland',
        'indien': 'india',
        'indonesien': 'indonesia',
        'iran': 'iran',
        'irak': 'iraq',
        'irland': 'ireland',
        'israel': 'israel',
        'italien': 'italy',
        'jamaika': 'jamaica',
        'japan': 'japan',
        'jordanien': 'jordan',
        'kasachstan': 'kazakhstan',
        'kenia': 'kenya',
        'kiribati': 'kiribati',
        'kosovo': 'kosovo',
        'kuwait': 'kuwait',
        'kirgisistan': 'kyrgyzstan',
        'laos': 'laos',
        'lettland': 'latvia',
        'libanon': 'lebanon',
        'lesotho': 'lesotho',
        'liberia': 'liberia',
        'libyen': 'libya',
        'liechtenstein': 'lichtenstein',
        'litauen': 'lithuania',
        'luxemburg': 'luxembourg',
        'mazedonien': 'macedonia',
        'madagaskar': 'madagascar',
        'malawi': 'malawi',
        'malaysia': 'malaysia',
        'Malediven': 'maldives',
        'mali': 'mali',
        'malta': 'malta',
        'mauretanien': 'mauritania',
        'mauritius': 'mauritius',
        'mexiko': 'mexico',
        'mikronesien': 'micronesia',
        'moldawien': 'moldova',
        'monaco': 'monaco',
        'mongolei': 'mongolia',
        'montenegro': 'montenegro',
        'marokko': 'morocco',
        'mosambik': 'mozambique',
        'myanmar': 'myanmar',
        'namibia': 'namibia',
        'nauru': 'nauru',
        'nepal': 'nepal',
        'neuseeland': 'new zealand',
        'nicaragua': 'nicaragua',
        'niger': 'niger',
        'nigeria': 'nigeria',
        'niue': 'niue',
        'nord korea': 'north korea',
        'norwegen': 'norway',
        'oman': 'oman',
        'pakistan': 'pakistan',
        'palau': 'palau',
        'panama': 'panama',
        'neu guinea': 'papua new guinea',
        'paraguay': 'paraguay',
        'peru': 'peru',
        'polen': 'poland',
        'portugal': 'portugal',
        'katar': 'qatar',
        'rumänien': 'romania',
        'russland': 'russia',
        'ruanda': 'rwanda',
        'heilige kitts': 'saint kitts',
        'heilige lucia': 'saint lucia',
        'heilige vincent': 'saint vincent',
        'samoa': 'samoa',
        'san marino': 'san marino',
        'sao tome and principe': 'sao tome and principe',
        'saudi arabien': 'saudi arabia',
        'zenegal': 'senegal',
        'serbien': 'serbia',
        'sierra leone': 'sierra leone',
        'singapur': 'singapore',
        'slowakei': 'slovakia',
        'slowenien': 'slovenia',
        'somalia': 'somalia',
        'südafrika': 'south africa',
        'südkorea': 'south korea',
        'südsudan': 'sudan',
        'spanien': 'spain',
        'sri lanka': 'sri lanka',
        'sudan': 'sudan',
        'surinam': 'suriname',
        'swasiland': 'swaziland',
        'schweden': 'sweden',
        'die schweiz': 'switzerland',
        'der schweiz': 'switzerland',
        'schweiz': 'switzerland',
        'syrien': 'syria',
        'taiwan': 'taiwan',
        'tadschikistan': 'tajikistan',
        'tansania': 'tanzania',
        'thailand': 'thailand',
        'die bahamas': 'the bahamas',
        'die zentralafrikanische republik': 'the central african republic',
        'die komoren': 'the comoros',
        'der kongo': 'the congo',
        'die tschechische republik': 'the czech republic',
        'die dominikanische republik': 'the dominican republic',
        'das gambia': 'the gambia',
        'die marshallinseln': 'the marshall islands',
        'die niederlande': 'the netherlands',
        'die phillipinen': 'the philippines',
        'die republik congo': 'the republic of the congo',
        'die seychellen': 'the seychelles',
        'die salomonen': 'the solomon islands',
        'die vereinigten arabischen emirate': 'the united arab emirates',
        'die vereinigten staaten': 'the united states',
        'der vatikan': 'the vatican',
        'äthiopien': 'Ethiopia',
        'togo': 'togo',
        'tonga': 'tonga',
        'trinidad': 'trinidad',
        'tunesien': 'tunisia',
        'türkei': 'turkey',
        'turkmenistan': 'turkmenistan',
        'tuvalu': 'tuvalu',
        'uganda': 'uganda',
        'ukraine': 'ukraine',
        'uruguay': 'uruguay',
        'usbekistan': 'uzbekistan',
        'vanuatu': 'vanuatu',
        'venezuela': 'venezuela',
        'vietnam': 'vietnam',
        'westsahara': 'western sahara',
        'jemen': 'yemen',
        'sambia': 'zambia',
        'simbabwe': 'zimbabwe',
      }
  }
