
      module.exports = {
          'HELLONEW_EN_US': {
                  "Hello, I\'m here to help with international calls. You can say things like: what is the dialing code for Spain, how do I call India, or which country has the dialing code <say-as digits='352'></say-as>? Now, how can I help?",
                  "Hi, you can ask me things like: what is the dialing code for Portugal, or how do I call Japan? What can I do for you?",
                  "Hello, I\'m here to help with international calls. You can say things like: what is the dialing code for Mexico, how do I call Belgium, or which country has the dialing code <say-as digits='352'></say-as>? Now, how can I help?",
                  "Hi, you can ask me things like: what is the dialing code for Luxembourg, or how do I call Germany? What can I do for you?",
                  "Hello, I\'m here to help with international calls. You can say things like: what is the dialing code for France, how do I call Great Britain, or which country has the dialing code <say-as digits='49'></say-as>? Now, how can I help?",
                },
                'HELLOPRO_EN_US': {
                  "<say-as interpret-as='interjection'>Howdy</say-as><break time='0.5s'/>, how can I help?",
                  "<say-as interpret-as='interjection'>Howdy</say-as><break time='0.5s'/>, how can I help?",
                  "<say-as interpret-as='interjection'>Howdy</say-as><break time='0.5s'/>, how can I help?",
                  "<say-as interpret-as='interjection'>Howdy</say-as><break time='0.5s'/>, how can I help?",
                  "<say-as interpret-as='interjection'>Howdy</say-as><break time='0.5s'/>, how can I help?",
                  "<say-as interpret-as='interjection'>Howdy</say-as><break time='0.5s'/>, how can I help?",
                  "<say-as interpret-as='interjection'>Howdy</say-as><break time='0.5s'/>, how can I help?",
                  "<say-as interpret-as='interjection'>Howdy</say-as><break time='0.5s'/>, how can I help?",
                },
                'MORE_EN_US':{
                  "Anything else?",
                  "Is there anything else you need?",
                  "Need anything else?",
                  "Anything more I can do?",
                  "What else can I do?",
                  "Can I help with anything else?",
                  "Can I assist you with anything else?",
                  "Need anything more?",
                  "Can I do anything else for you now?",
                },
                'ERRCON_EN_US':{
                  "<say-as interpret-as='interjection'>Argh, </say-as>",
                  "<say-as interpret-as='interjection'>Aw man, </say-as>",
                  "<say-as interpret-as='interjection'>Blast, </say-as>",
                  "<say-as interpret-as='interjection'>Bummer, </say-as>",
                  "<say-as interpret-as='interjection'>Darn, </say-as>",
                  "<say-as interpret-as='interjection'>Eek, </say-as>",
                  "<say-as interpret-as='interjection'>Good grief, </say-as>",
                  "<say-as interpret-as='interjection'>Heads up, </say-as>",
                  "<say-as interpret-as='interjection'>Oh boy, </say-as>",
                  "<say-as interpret-as='interjection'>Oh snap, </say-as>",
                  "<say-as interpret-as='interjection'>Uh oh, </say-as>",
                  "<say-as interpret-as='interjection'>Whoops a daisy, </say-as>",
                },
                'ERRMSG':{
                  "something went wrong, please try that again.",
                  "something went wrong. Are you using a valid country name or dialing code?",
                  "I couldn\'t find anything for that, please try again.",
                  "I'm stuck, please make sure you\'re using a valid country name.",
                  "this looks wrong, please check the info you\'re giving me.",
                  "that didn\'t work, please try again.",
                  "something went wrong, please try that again.",
                  "I couldn\'t find the info. Please use a valid country name.",
                },
                'HELP_EN_US':{
                    "You can say things like: what is the dialing code for Spain, how do I call India, or which country has the dialing code <say-as digits='352'></say-as>? Now, how can I help?",
                    "You can ask me things like: what is the dialing code for Portugal, or how do I call Japan? What can I do for you?",
                    "I\'m here to help with international calls. You can say things like: what is the dialing code for Mexico, how do I call Belgium, or which country has the dialing code <say-as digits='352'></say-as>? Now, how can I help?",
                    "You can ask me things like: what is the dialing code for Luxembourg, or how do I call Germany? What can I do for you?",
                    "You can say things like: what is the dialing code for France, how do I call Great Britain, or which country has the dialing code <say-as digits='49'></say-as>? Now, how can I help?",
                },
                'GOODBYE_EN_US':{
                  "Okay bye for now.",
                  "<say-as interpret-as='interjection'>As you wish.</say-as>",
                  "Very well, have a good day.",
                  "<say-as interpret-as='interjection'>Roger</say-as> that.",
                  "Sure. See you later.",
                  "Okay, no worries.",
                  "Okay, goodbye.",
                  "Okay, so long.",
                  "Okay bye, bye.",
                  "Okay, take care."
                },
            }
